version: "2"
services:
  db:
    image: postgres:12
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      PGPASSWORD: password
    volumes:
      - ./sql:/sql
